import React from "react";

import { ConnectWalletButton } from "./";

export type Route = {
  name: string;
  href: string;
};

type HeaderProps = {
  routes?: Route[];
};

const Header = ({ routes = [] }: HeaderProps) => {
  return (
    <header className="bg-eco-blue-dark mb-4">
      <div>
        <title>{process.env.NEXT_PUBLIC_DAPP_NAME}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </div>
      <nav className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8" aria-label="Top">
        <div className="w-full py-6 flex items-center justify-between border-b border-eco-blue-primary lg:border-none">
          <div className="flex items-center">
            <a href="/">
              <span className="sr-only">Workflow</span>
              <img
                className="h-8 w-auto"
                src="/white_logo_text.svg"
                alt="logo"
              />
            </a>
            <div className="hidden ml-10 space-x-8 lg:block">
              {routes.map((route) => (
                <a
                  key={route.name}
                  href={route.href}
                  className="text-base font-medium text-white hover:text-eco-teal-accent"
                >
                  {route.name}
                </a>
              ))}
            </div>
          </div>
          <ConnectWalletButton intent="none" kind="hollow" />
        </div>
        <div className="py-4 flex flex-wrap justify-center space-x-6 lg:hidden">
          {routes.map((route) => (
            <a
              key={route.name}
              href={route.href}
              className="text-base font-medium text-white hover:text-eco-teal-accent"
            >
              {route.name}
            </a>
          ))}
        </div>
      </nav>
    </header>
  );
};

export default Header;
